### ISSUE TITLE
failed to parse multiline string in YAML frontmatter

### ISSUE THREAD

**Issue by johnnychen94** [johnnychen94/DemoCards.jl#51]
This is a valid YAML syntax
```yaml
title: mnist_elastic
id: mnist_elastic
description: >
             In this example we are going to use Augmentor on the famous **MNIST database of handwritten digits**
             [^MNIST1998] to reproduce the elastic distortions discussed in [^SIMARD2003].
```

but it fails to parse when I add this to the julia script as a frontmatter:

```julia
# ---
# title: mnist_elastic
# id: mnist_elastic
# description: >
#              In this example we are going to use Augmentor on the famous **MNIST database of handwritten digits**
#              [^MNIST1998] to reproduce the elastic distortions discussed in [^SIMARD2003].
# ---
```

similar to #48, I should not remove the leading whitespace in 
https://github.com/johnnychen94/DemoCards.jl/blob/a2ee88b77147f1f17c1e3c1a973f98d0b5dc7230/src/utils.jl#L256
